# Generated by Django 5.0.7 on 2024-10-29 06:18

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your phone number with country code.', max_length=128, region='GB', verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('f_name', models.CharField(max_length=255)),
                ('f_message', models.TextField(max_length=2255)),
                ('f_email', models.EmailField(max_length=255)),
                ('f_reply', models.TextField(default='Hi Friend, Thank you For you feedback!!!', max_length=2255)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
